In [6]:
import pandas as pd

df = pd.read_csv("arxiv_jet_papers.csv", parse_dates=["published"])

In [17]:
#Lund plane and theory
df[df.title.str.contains("lund", case=False, na=False) & df.category.str.contains("hep-ph")]

,arxiv_id,published,title,authors,category,matched_keywords,url,abstract
88,2605.26821v1,2026-05-26,Particle-Lund Multimodality in Jet Taggers,Loukas Gouskos; Benedikt Maier,hep-ph,"jet, lund plane",http://arxiv.org/abs/2605.26821v1,"The Lund plane offers a physics-motivated, hie..."
184,2604.25885v1,2026-04-28,Explainable AI for Jet Tagging: A Comparative ...,Pahal D. Patel; Sanmay Ganguly,hep-ph,"jet, lund plane, jet substructure, non-perturb...",http://arxiv.org/abs/2604.25885v1,Graph neural networks such as ParticleNet and ...
683,2512.17408v1,2025-12-19,The Lund $b$-jet plane,Andrea Ghira; Simone Marzani; Gregory Soyez,hep-ph,"jet, lund plane, resummation",http://arxiv.org/abs/2512.17408v1,We compute the primary Lund plane density for ...
809,2511.16723v1,2025-11-20,A new suite of Lund-tree observables to resolv...,Melissa van Beekveld; Luca Buonocore; Silvia F...,hep-ph,"jet, event shape, parton shower",http://arxiv.org/abs/2511.16723v1,"We introduce a class of collider observables, ..."
1109,2509.02348v1,2025-09-02,Herwig 7 with the Lund String Model: Tuning an...,Michaela Divisova; Miroslav Myska; Pratixan Sa...,hep-ph,"parton shower, non-perturbative",http://arxiv.org/abs/2509.02348v1,The modelling of the formation of colour-singl...

In [24]:
# energy correlators by Ian and Kyle
df[df.title.str.contains("energy correlator", case=False, na=False) & df.category.str.contains("hep-ph") & (df.authors.str.contains("Lee", case=False, na=False) | df.authors.str.contains("Moult", case=False, na=False))]

,arxiv_id,published,title,authors,category,matched_keywords,url,abstract
64,2606.02714v1,2026-06-01,Projected Energy Correlators: Two-Loop Jet Fun...,Kyle Lee; Yibei Li; Zhen Xu; Xiaoyuan Zhang,hep-ph,"jet, energy correlator, resummation, non-pertu...",http://arxiv.org/abs/2606.02714v1,We present the next-to-next-to-leading logarit...
200,2604.21971v1,2026-04-23,Hydrodynamics and Energy Correlators,João Barata; Matvey V. Kuzmin; Ian Moult; Andr...,hep-ph,"energy-energy correlator, energy correlator",http://arxiv.org/abs/2604.21971v1,We study energy-energy correlators (EECs) in m...
542,2601.20933v1,2026-01-28,Precision Jet Substructure of Boosted Boson De...,Anjie Gao; Kyle Lee; Xiaoyuan Zhang,hep-ph,"jet, jet substructure, energy correlator",http://arxiv.org/abs/2601.20933v1,We initiate the precision study of boosted jet...
543,2601.20923v2,2026-01-28,High precision heavy-boson-jet substructure wi...,Jack Holguin; Ian Moult; Aditya Pathak; Massim...,hep-ph,"jet, jet substructure, energy correlator, resu...",http://arxiv.org/abs/2601.20923v2,Energy-correlator-based jet substructure has g...
714,2512.11950v1,2025-12-12,From DGLAP to Sudakov: Precision Predictions f...,Max Jaarsma; Yibei Li; Ian Moult; Wouter J. Wa...,hep-ph,"energy-energy correlator, energy correlator, r...",http://arxiv.org/abs/2512.11950v1,Correlations in the distribution of energy pro...
884,2511.00149v1,2025-10-31,Energy Correlators from Partons to Hadrons: Un...,Hannah Bossi; Yi Chen; Yu-Chen Chen; Max Jaars...,hep-ph,energy correlator,http://arxiv.org/abs/2511.00149v1,Quantum Chromodynamics (QCD) is a remarkably r...
1075,2509.08047v1,2025-09-09,Imaging the Jet-Induced Medium Response with E...,Hannah Bossi; Arjun Kudinoor; Ian Moult; Danie...,hep-ph,"jet, energy-energy correlator, energy correlat...",http://arxiv.org/abs/2509.08047v1,"Quark-gluon plasma (QGP), when viewed at lengt..."
1131,2508.19404v1,2025-08-26,Heavy Quark Pair Energy Correlators: From Prof...,João Barata; Jasmine Brewer; Kyle Lee; João M....,hep-ph,"energy correlator, resummation",http://arxiv.org/abs/2508.19404v1,"We introduce heavy-flavor energy correlators, ..."
1278,2507.11495v3,2025-07-15,Dihadron Fragmentation and the Confinement Tra...,Kyle Lee; Iain Stewart,hep-ph,"jet, energy-energy correlator, energy correlator",http://arxiv.org/abs/2507.11495v3,"In this letter, we relate the factorization fo..."

In [10]:

# multiple keywords (OR)
mask = df.abstract.str.contains("renormalon|power correction", case=False, na=False)
df[mask]

,arxiv_id,published,title,authors,category,matched_keywords,url,abstract
142,2605.06996v1,2026-05-07,Renormalon-based resummation for B(D) Mesons,Cesar Ayala; Gorazd Cvetic,hep-ph,resummation,http://arxiv.org/abs/2605.06996v1,We apply a previously developed method of reno...
145,2605.06567v1,2026-05-07,Probing unknown nonperturbative effects in $b ...,P. Alvarez-Cartelle; B. Capdevila; E. Lunghi; ...,hep-ph,"non-perturbative, power correction",http://arxiv.org/abs/2605.06567v1,"In this paper we revisit, from a different per..."
155,2605.04001v2,2026-05-05,QCD sum rules: Borel parameter vs. Euclidean time,A. V. Smilga,hep-ph,power correction,http://arxiv.org/abs/2605.04001v2,We explore a modification of QCD sum rules whe...
182,2604.25998v1,2026-04-28,New insights into the $b\rightarrow c \bar{u}q...,Jack Y. Araz; Christoph Englert; Matthew Kirk;...,hep-ph,power correction,http://arxiv.org/abs/2604.25998v1,Anomalies in the non-leptonic $\bar{B}^0\right...
215,2604.18443v1,2026-04-20,New Physics in inclusive $\bar{B} \to X_c \ell...,Alexandre Carvunis; Gael Finauri; Paolo Gambin...,hep-ph,"non-perturbative, power correction",http://arxiv.org/abs/2604.18443v1,We present the first global phenomenological f...
243,2604.13439v2,2026-04-15,A Core Representation Theorem for Scheme-Invar...,Dustin Keller,hep-ph,"non-perturbative, power correction",http://arxiv.org/abs/2604.13439v2,Collinear factorization and the leading-twist ...
248,2604.11967v1,2026-04-13,Operator structure of power corrections and an...,Hao Chen; Yibei Li,hep-ph,"jet, energy-energy correlator, energy correlat...",http://arxiv.org/abs/2604.11967v1,Energy correlators offer a clean probe of quan...
299,2604.00143v1,2026-03-31,Proton isovector helicity PDF at NNLO and the ...,Xiang Gao; Andrew D. Hanlon; Swagato Mukherjee...,hep-lat,resummation,http://arxiv.org/abs/2604.00143v1,We present a lattice quantum chromodynamics ca...
339,2603.22072v1,2026-03-23,A perturbative framework to probe infrared sen...,Duarte Fontes; Dennis Horstmann; Kirill Melnik...,hep-ph,"non-perturbative, power correction",http://arxiv.org/abs/2603.22072v1,Understanding the infrared sensitivity of pert...
350,2603.19833v1,2026-03-20,Factorization theorem for quasi-TMD distributi...,Alejandro Bris Cuerpo; Arturo Arroyo-Castro; A...,hep-ph,power correction,http://arxiv.org/abs/2603.19833v1,We derive the factorization theorem for the qu...
355,2603.19162v1,2026-03-19,A global analysis of Energy-Energy Correlation...,Ugo Giuseppe Aglietti; Giancarlo Ferrera; Lore...,hep-ph,"jet, resummation, non-perturbative, power corr...",http://arxiv.org/abs/2603.19162v1,We present a comprehensive global analysis of ...
361,2603.16996v1,2026-03-17,Higher-point Energy Correlators: Factorization...,Ankita Budhraja; Isabelle Pels; Wouter J. Waal...,hep-ph,"jet, energy-energy correlator, energy correlat...",http://arxiv.org/abs/2603.16996v1,N-point energy correlators are powerful observ...
452,2602.20249v1,2026-02-23,Resummed azimuthal decorrelation and transvers...,Rong-Jun Fu; Rudi Rahn; Ding Yu Shao; Wouter J...,hep-ph,"jet, resummation, non-perturbative, power corr...",http://arxiv.org/abs/2602.20249v1,We present a theoretical study of the azimutha...
477,2602.15331v1,2026-02-17,Higher-twist effect in inclusive electron-posi...,Jing Zhao; Yongjie Deng; Tianbo Liu; Weihua Yang,hep-ph,power correction,http://arxiv.org/abs/2602.15331v1,We establish a comprehensive theoretical frame...
519,2602.04639v1,2026-02-04,Estimating power corrections for the Drell-Yan...,Ekta Chaubey; Pooja Mukherjee,hep-ph,power correction,http://arxiv.org/abs/2602.04639v1,We study power corrections in the Drell-Yan (D...
651,2512.21091v1,2025-12-24,Renormalized tropical field theory,Paul-Hermann Balduf; Erik Panzer,math-ph,power correction,http://arxiv.org/abs/2512.21091v1,We introduce tropical scalar field theory as a...
665,2512.19138v1,2025-12-22,The Standard Model Prediction for the Rare Dec...,Matteo Fael; Jack Jenkins; Enrico Lunghi; Zach...,hep-ph,"non-perturbative, power correction",http://arxiv.org/abs/2512.19138v1,We present updated and comprehensive Standard ...
669,2512.18866v2,2025-12-21,Next-to-Next-to-Leading-Order Corrections to t...,Yong-Kang Huang; Dong-Hao Li; Cai-Dian Lü; Bo-...,hep-ph,power correction,http://arxiv.org/abs/2512.18866v2,By incorporating the available leading-power r...
731,2512.09888v1,2025-12-10,A Precise $α_s$ Determination from the R-impro...,Jose M. Mena-Valle,hep-ph,resummation,http://arxiv.org/abs/2512.09888v1,The strong coupling $α_s$ is extracted with hi...
754,2512.05795v2,2025-12-05,Three-loop jet function for boosted top quarks,Alberto M. Clavero; Vicent Mateu; Maximilian S...,hep-ph,jet,http://arxiv.org/abs/2512.05795v2,We present the calculation of the inclusive je...
777,2511.23423v2,2025-11-28,IRC-safe jet flavour at leading power,Terry Generet,hep-ph,"jet, power correction",http://arxiv.org/abs/2511.23423v2,We derive the leading power quark mass effects...
821,2511.14387v2,2025-11-18,Parton distributions with higher twist and jet...,Richard D. Ball; Amedeo Chiefa; Roy Stegeman,hep-ph,"jet, power correction",http://arxiv.org/abs/2511.14387v2,We present a global determination of parton di...
905,2510.24846v1,2025-10-28,A Precise $α_s$ Determination from the R-impro...,Jose M. Mena-Valle; Vicent Mateu; Pablo G. Ortega,hep-ph,resummation,http://arxiv.org/abs/2510.24846v1,The strong coupling $α_s$ is determined with h...
925,2510.21435v1,2025-10-24,Determination of the strong coupling from high...,S. Alekhin; M. V. Garzelli; S. Moch; O. Zenaiev,hep-ph,power correction,http://arxiv.org/abs/2510.21435v1,We determine the strong coupling from high-ene...
950,2510.14496v1,2025-10-16,Kinematic power corrections for TMD factorizat...,Sara Piloneta; Alexey Vladimirov,hep-ph,power correction,http://arxiv.org/abs/2510.14496v1,We evaluate the complete set of kinematic powe...
955,2510.13571v2,2025-10-15,Parton model contributions as next-to-eikonal ...,Tolga Altinoluk; Guillaume Beuf; Swaleha Mulani,hep-ph,power correction,http://arxiv.org/abs/2510.13571v2,We compute the next-to-eikonal (NEik) power co...
959,2510.12193v1,2025-10-14,Gradient-flowed operator product expansion wit...,Martin Beneke; Hiromasa Takaura,hep-ph,"non-perturbative, power correction",http://arxiv.org/abs/2510.12193v1,A long-standing problem concerns the question ...
994,2510.03097v1,2025-10-03,Power corrections to the production of a promp...,Prem Agarwal; Kirill Melnikov; Ivan Pedron,hep-ph,"jet, power correction",http://arxiv.org/abs/2510.03097v1,We compute the next-to-leading-power correctio...
1005,2509.24746v1,2025-09-29,The real-time QCD static potential at high tem...,Margaret E. Carrington; Cristina Manuel; Joan ...,hep-ph,power correction,http://arxiv.org/abs/2509.24746v1,We develop a procedure to analytically calcula...
1012,2509.22782v1,2025-09-26,Toward the Analytic Bootstrap of Energy Correl...,Jianyu Gong; Andrzej Pokraka; Kai Yan; Xiaoyua...,hep-ph,"energy correlator, power correction",http://arxiv.org/abs/2509.22782v1,"In this paper, we present a framework for the ..."
1063,2509.12056v2,2025-09-15,Method of regions for dual conformal integrals,Leonid V. Bork; Roman N. Lee; Andrei I. Onishc...,hep-th,power correction,http://arxiv.org/abs/2509.12056v2,We apply the method of regions to the evaluati...
1071,2509.09042v2,2025-09-10,Renormalon-based resummation for spacelike and...,Cesar Ayala; Gorazd Cvetič; Reinhart Kögerler,hep-ph,resummation,http://arxiv.org/abs/2509.09042v2,We present a generalisation of our previous ap...
1088,2509.06669v2,2025-09-08,Constraining the Energy Momentum Tensor throug...,Víctor Martínez-Fernández; Daniele Binosi; Céd...,hep-ph,power correction,http://arxiv.org/abs/2509.06669v2,"In this letter, we analyse and interpret the k..."
1098,2509.05059v3,2025-09-05,Dispersion relations of deeply virtual Compton...,Víctor Martínez-Fernández; Cédric Mezrag,hep-ph,power correction,http://arxiv.org/abs/2509.05059v3,In this paper we include kinematic power corre...
1106,2509.02977v1,2025-09-03,The role of the soft scale for $J/ψ$ productio...,Marston Copeland; Sean Fleming; Reed Hodges,hep-ph,power correction,http://arxiv.org/abs/2509.02977v1,We use vNRQCD to study power corrections in th...
1119,2509.00247v2,2025-08-29,Improving the Precision of First-Principles Ca...,Yong Zhao,hep-lat,"resummation, non-perturbative, power correction",http://arxiv.org/abs/2509.00247v2,Large Momentum Effective Theory (LaMET) provid...
1169,2508.09986v2,2025-08-13,Data-driven analyses and model-independent fit...,T. Hurth; F. Mahmoudi; Y. Monceaux; S. Neshatpour,hep-ph,power correction,http://arxiv.org/abs/2508.09986v2,We present a critical assessment of the presen...
1177,2508.05741v1,2025-08-07,Factorization and resummation of QED radiative...,Zehua Cao; Richard J. Hill; Ryan Plestid; Pete...,hep-ph,"jet, resummation, power correction",http://arxiv.org/abs/2508.05741v1,Details of the two-loop analysis of long-dista...
1286,2507.08926v3,2025-07-11,Renormalization-group equations of the LEFT at...,Luca Naterop; Peter Stoffer,hep-ph,power correction,http://arxiv.org/abs/2507.08926v3,We present the third part of a systematic calc...
1313,2507.02605v2,2025-07-03,Trans-series from condensates in the non-linea...,Yizhuang Liu; Marcos Mariño,hep-th,non-perturbative,http://arxiv.org/abs/2507.02605v2,In this work we provide a massless perturbativ...

In [11]:
# filter by your matched_keywords column
df[df.matched_keywords.str.contains("jet substructure", na=False)]

,arxiv_id,published,title,authors,category,matched_keywords,url,abstract
1,2606.19068v1,2026-06-17,High-$p_{\rm T}$ physics and jet production,Francesco Giuli,hep-ex,"jet, jet substructure, non-perturbative",http://arxiv.org/abs/2606.19068v1,Jet production is the dominant high-$p_{\rm T}...
4,2606.18093v1,2026-06-16,Probing jet evolution with charged energy corr...,ALICE Collaboration,nucl-ex,"jet, jet substructure, energy-energy correlato...",http://arxiv.org/abs/2606.18093v1,The ALICE Collaboration presents measurements ...
44,2606.06603v1,2026-06-04,Reweighting Adversarial Networks for Unbinned ...,Umar Sohail Qureshi; Krish Desai; Jesse Thaler...,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2606.06603v1,Differential cross sections are the currency o...
143,2605.06789v2,2026-05-07,Physics inspired quantum algorithm for QCD spl...,Gabriel Rouxinol; Yacine Haddad; Cenk Tüysüz; ...,quant-ph,"jet, jet substructure",http://arxiv.org/abs/2605.06789v2,We introduce a modular quantum circuit primiti...
159,2605.03063v2,2026-05-04,From Information Geometry to Jet Substructure:...,Aritra Bal; Markus Klute; Benedikt Maier; Mich...,hep-ph,"jet, jet substructure, energy correlator",http://arxiv.org/abs/2605.03063v2,Pairwise Fisher graphs capture local covarianc...
184,2604.25885v1,2026-04-28,Explainable AI for Jet Tagging: A Comparative ...,Pahal D. Patel; Sanmay Ganguly,hep-ph,"jet, lund plane, jet substructure, non-perturb...",http://arxiv.org/abs/2604.25885v1,Graph neural networks such as ParticleNet and ...
185,2604.25538v1,2026-04-28,Simultaneous measurements of $N$-subjettiness ...,CMS Collaboration,hep-ex,"jet, jet substructure",http://arxiv.org/abs/2604.25538v1,A simultaneous measurement of 25 substructure ...
186,2604.25490v1,2026-04-28,Les Houches study on inclusive jet production ...,Terry Generet; Joey Huston; Kyle Lee; Ian Moul...,hep-ph,"jet, jet substructure, resummation, non-pertur...",http://arxiv.org/abs/2604.25490v1,Jet production at the LHC is a powerful probe ...
203,2604.20965v1,2026-04-22,Kitchen Sink Anomaly Detection,Ranit Das; Marie Hein; Gregor Kasieczka; Micha...,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2604.20965v1,An enormous amount of R&D effort has resulted ...
240,2604.18613v1,2026-04-15,Lund Plane to Bloch (LP2B) Encoding for Object...,Fabrizio Napolitano; Luca Della Penna; Tommaso...,quant-ph,"jet, lund plane, jet substructure, parton show...",http://arxiv.org/abs/2604.18613v1,The application of quantum algorithms to jet s...
298,2604.00617v1,2026-04-01,Searching for New Physics Inside Jets with the...,Taehee Kim; Joon-Bin Lee; M. R. Masouminia; Mi...,hep-ph,"jet, jet substructure, parton shower",http://arxiv.org/abs/2604.00617v1,This study investigates parton shower evolutio...
313,2603.27846v2,2026-03-29,Full energy fraction and angular dependence of...,Carlota Andres; Fabio Dominguez,hep-ph,"jet, jet substructure, resummation",http://arxiv.org/abs/2603.27846v2,Jets produced in relativistic heavy-ion collis...
316,2603.26595v1,2026-03-27,PQuantML: A Tool for End-to-End Hardware-aware...,Roope Niemi; Anastasiia Petrovych; Arghya Ranj...,cs.LG,"jet, jet substructure",http://arxiv.org/abs/2603.26595v1,"PQuantML is a new open-source, hardware-aware ..."
333,2603.23596v1,2026-03-24,A Breath of Fresh Air for Molière: Detecting M...,Arjun Srinivasan Kudinoor; Arthur Yi-Ting Lin;...,hep-ph,"jet, jet substructure, energy-energy correlato...",http://arxiv.org/abs/2603.23596v1,Ultra-relativistic oxygen-oxygen (OO) collisio...
340,2603.22014v1,2026-03-23,Jet quenching and its substructure dependence ...,Xiang-Pan Duan; Lin Chen; Guo-Liang Ma; Carlos...,hep-ph,"jet, jet substructure, jet quenching",http://arxiv.org/abs/2603.22014v1,Motivated by color coherence and decoherence e...
420,2603.03689v1,2026-03-04,Measurement of angular correlations inside jet...,CMS Collaboration,hep-ex,"jet, jet substructure, parton shower",http://arxiv.org/abs/2603.03689v1,A study of angular correlations inside jets in...
433,2602.24282v1,2026-02-27,"Unfolding without Iterations, Adversaries, or ...",Ayodele Ore; Tilman Plehn,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2602.24282v1,Correcting measurements for detector effects a...
451,2602.20477v2,2026-02-24,Search for pair production of heavy resonances...,CMS Collaboration,hep-ex,"jet, jet substructure",http://arxiv.org/abs/2602.20477v2,A search for the pair production of heavy spin...
539,2602.00141v1,2026-01-29,Comparison of Image Processing Models in Quark...,Daeun Kim; Jiwon Lee; Wonjun Jeong; Hyeongwoo ...,physics.data-an,"jet, jet substructure",http://arxiv.org/abs/2602.00141v1,We present a comprehensive comparison of convo...
542,2601.20933v1,2026-01-28,Precision Jet Substructure of Boosted Boson De...,Anjie Gao; Kyle Lee; Xiaoyuan Zhang,hep-ph,"jet, jet substructure, energy correlator",http://arxiv.org/abs/2601.20933v1,We initiate the precision study of boosted jet...
543,2601.20923v2,2026-01-28,High precision heavy-boson-jet substructure wi...,Jack Holguin; Ian Moult; Aditya Pathak; Massim...,hep-ph,"jet, jet substructure, energy correlator, resu...",http://arxiv.org/abs/2601.20923v2,Energy-correlator-based jet substructure has g...
546,2601.19645v2,2026-01-27,Discriminating QCD Compton and Quark-Antiquark...,Monalini Samal; Nihar Ranjan Sahoo,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2601.19645v2,We investigate how effectively final-state jet...
570,2601.13310v1,2026-01-19,Bottom-up approach to describe groomed jet dat...,Liliana Apolinário; Diogo Costa; Alba Soto-Ontoso,hep-ph,"jet, jet substructure, parton shower, non-pert...",http://arxiv.org/abs/2601.13310v1,The theoretical interpretation of jet observab...
571,2601.13257v1,2026-01-19,Measurement of multi-jets and vector boson plu...,Giulia Manco,hep-ex,"jet, jet substructure",http://arxiv.org/abs/2601.13257v1,The production of multiple jets or vector boso...
585,2601.10871v1,2026-01-15,Topic Modeling in New Physics Detection,Alexandre Alves; Eduardo da Silva Almeida; Dou...,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2601.10871v1,"In this work, we apply topic modeling to detec..."
619,2601.01450v1,2026-01-04,Topology-Informed Jet Tagging using Persistent...,Saurav Mittal,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2601.01450v1,We present a topology-informed approach for cl...
691,2512.16180v1,2025-12-18,Fatjet Signatures of Quintuplet Fermions at th...,Sourabh Dube; Nilanjana Kumar; Shriyansh Ranjan,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2512.16180v1,This paper explores a simplified extension of ...
702,2512.14053v1,2025-12-16,Substructure grooming of inclusive and photon-...,Sa Wang; Shuang Li; Jin-Wen Kang; Ben-Wei Zhan...,hep-ph,"jet, jet substructure, soft drop, grooming",http://arxiv.org/abs/2512.14053v1,Jet substructure provides a powerful probe of ...
711,2512.12318v1,2025-12-13,Interference Effects in Resonant Standard Mode...,A. Hammad; S. Moretti; A. P. Przybyl; H. Waltari,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2512.12318v1,The final state with four $b$-quarks has gener...
728,2512.10026v1,2025-12-10,Living on the edge: radius effects in the angu...,Carlota Andres; Jack Holguin; Benjamin Kimelma...,hep-ph,"jet, jet substructure, energy correlator",http://arxiv.org/abs/2512.10026v1,Jet substructure observables serve as essentia...
774,2512.00210v1,2025-11-28,Why Is Attention Sparse In Particle Transformer?,Timothy Legge; Aaron Wang; Jacob Ortiz; Victor...,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2512.00210v1,Transformer-based models have achieved state-o...
822,2511.13495v1,2025-11-17,Medium modification of the charge-weighted Ene...,Han-Yao Liu; Shi-Yong Chen; Wei Dai; Ben-Wei Z...,nucl-th,"jet, jet substructure, energy-energy correlato...",http://arxiv.org/abs/2511.13495v1,We present a systematic study of medium-induce...
833,2511.10588v1,2025-11-13,Probing jet hadrochemistry modification with m...,Sierra Cantway,nucl-ex,"jet, jet substructure, jet quenching",http://arxiv.org/abs/2511.10588v1,Measurements of jet substructure observables i...
848,2511.07519v2,2025-11-10,Jet quenching in out-of-equilibrium QCD matter,João Barata; Kirill Boguslavski; Florian Linde...,hep-ph,"jet, jet substructure, jet quenching",http://arxiv.org/abs/2511.07519v2,We present the first study of jet substructure...
858,2511.10666v2,2025-11-06,Jet fragmentation function and groomed substru...,CMS Collaboration,hep-ex,"jet, jet substructure",http://arxiv.org/abs/2511.10666v2,A measurement of the substructure of bottom qu...
863,2511.04005v3,2025-11-06,Validating a Machine Learning Approach to Iden...,Yilun Wu; Yi Chen; Julia Velkovska,hep-ph,"jet, jet substructure, parton shower, jet quen...",http://arxiv.org/abs/2511.04005v3,Jet quenching is a phenomenon in heavy-ion col...
929,2510.19906v2,2025-10-22,Generative Unfolding of Jets and Their Substru...,Antoine Petitjean; Anja Butter; Kevin Greif; S...,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2510.19906v2,"Unfolding, for example of distortions imparted..."
938,2510.17675v2,2025-10-20,Probing the Higgs Portal to a Strongly-Interac...,Cesare Cazzaniga; Annapaola de Cosa; Felix Kah...,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2510.17675v2,This work explores exotic signatures from conf...
946,2510.16195v1,2025-10-17,Energy-energy correlators in jets across colli...,Anjali Nambrath,nucl-ex,"jet, jet substructure, energy-energy correlato...",http://arxiv.org/abs/2510.16195v1,The two-point energy-energy correlator (EEC) i...
980,2510.06314v1,2025-10-07,Energy-Energy Flow Networks,Arianna Garcia Caffaro; Ian Moult; Chase Shimmin,hep-ph,"jet, jet substructure, energy correlator, part...",http://arxiv.org/abs/2510.06314v1,Jet substructure provides one of the most exci...
988,2510.04895v1,2025-10-06,Internal multiplicity distributions of jets fr...,Pi Duan; Weiyao Ke; Guang-You Qin; Lei Wang,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2510.04895v1,Jets selected with high internal charged-parti...
992,2510.03704v1,2025-10-04,Searching for New Physics with the Large Hadro...,Michael Spannowsky,hep-ph,"jet, jet substructure, grooming, parton shower",http://arxiv.org/abs/2510.03704v1,This chapter provides an introduction to colli...
993,2510.03390v1,2025-10-03,First Demonstration that Quark-Gluon Plasma ha...,Arjun Srinivasan Kudinoor; Daniel Pablos; Kris...,hep-ph,"jet, jet substructure, soft drop, grooming, pa...",http://arxiv.org/abs/2510.03390v1,We report on our investigation in arXiv:2509.0...
1043,2509.15809v3,2025-09-19,Accessing nucleon transversity with one-point ...,Mei-Sen Gao; Zhong-Bo Kang; Wanchen Li; Ding Y...,hep-ph,"jet, jet substructure, energy correlator",http://arxiv.org/abs/2509.15809v3,We propose a novel probe of the nucleon's tran...
1053,2509.14960v2,2025-09-18,Gluon Polarimetry with Energy-Energy Correlators,Yu-Kun Song; Shu-Yi Wei; Lei Yang; Jian Zhou,hep-ph,"jet, jet substructure, energy-energy correlato...",http://arxiv.org/abs/2509.14960v2,We propose a novel method to probe gluon linea...
1072,2509.08881v1,2025-09-10,Constraining the Resolution Length of Quark-Gl...,Arjun Srinivasan Kudinoor; Daniel Pablos; Kris...,hep-ph,"jet, jet substructure, soft drop, grooming, pa...",http://arxiv.org/abs/2509.08881v1,We show that recent measurements of substructu...
1092,2509.06370v1,2025-09-08,Neural Posterior Unfolding,Fernando Torales Acosta; Jay Chan; Krish Desai...,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2509.06370v1,Differential cross section measurements are th...
1111,2509.01736v3,2025-09-01,Multimodal Generative Flows for LHC Jets,Darius A. Faroughy; Manfred Opper; Cesar Ojeda,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2509.01736v3,Generative modeling of high-energy collisions ...
1152,2508.14987v1,2025-08-20,Probing jet hadrochemistry in Pb--Pb collision...,Sierra Cantway,nucl-ex,"jet, jet substructure, jet quenching",http://arxiv.org/abs/2508.14987v1,Jet substructure measurements in heavy-ion col...
1155,2508.14700v1,2025-08-20,Jets at electron-positron colliders,Giovanni Stagnitto,hep-ph,"jet, jet substructure, event shape, soft drop,...",http://arxiv.org/abs/2508.14700v1,We provide a pedagogical introduction to the p...
1203,2507.23610v1,2025-07-31,Jet substructure measurements elucidating part...,Monika Robotkova,hep-ex,"jet, jet substructure, energy correlator, non-...",http://arxiv.org/abs/2507.23610v1,Jets are multiscale objects that connect parto...
1216,2507.21613v2,2025-07-29,One-Point energy correlator inside jets,Zihao Mi; Zhan Wang,hep-ph,"jet, jet substructure, energy correlator, non-...",http://arxiv.org/abs/2507.21613v2,"In this work, we introduce a new jet observabl..."
1253,2507.15945v1,2025-07-21,Extracting Essential Non-perturbative Informat...,Zhan Gao; Yu Shi; Bo-Wen Xiao; Han-Zhong Zhang,hep-ph,"jet, jet substructure, non-perturbative",http://arxiv.org/abs/2507.15945v1,"In this paper, we present a new three-dimensio..."
1262,2507.15084v1,2025-07-20,Simulation-Prior Independent Neural Unfolding ...,Anja Butter; Theo Heimel; Nathan Huetsch; Mich...,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2507.15084v1,Machine learning allows unfolding high-dimensi...
1298,2507.06291v1,2025-07-08,High-Dimensional Unfolding in Large Backgrounds,Alexandre Falcão; Adam Takacs,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2507.06291v1,We propose new methodologies in multi-dimensio...
1307,2507.03199v3,2025-07-03,Improving sensitivity of vectorlike top partne...,Anupam Ghosh; Soumyadip Ghosh; Soureek Mitra; ...,hep-ph,"jet, jet substructure, event shape",http://arxiv.org/abs/2507.03199v3,Vectorlike quark partners appear in many BSM m...
1311,2507.02725v2,2025-07-03,Constraining color-charge effects of partonic ...,Raghunath Pradhan; Olga Evdokimov,hep-ph,"jet, jet substructure, jet quenching",http://arxiv.org/abs/2507.02725v2,This study investigates the color-charge depen...
1321,2507.00905v1,2025-07-01,Interplay of prompt and non-prompt photons in ...,Chathuranga Sirimanna; Yasuki Tachibana; Abhij...,hep-ph,"jet, jet substructure",http://arxiv.org/abs/2507.00905v1,Prompt photons are important yet challenging t...